### PR TITLE
Fixes watch app iTunes submission errors

### PR DESCRIPTION
**Pull request by digitalfx**
The Watch app version should equal the host app version

### CODE REVIEW

**Comment by digitalfx** [comment]
This is regarding [2879](https://hipbyte.freshdesk.com/helpdesk/tickets/2879)

**Comment by digitalfx** [comment]
I'm wondering whether outside of the original issue, it might make sense for this to be applied to all extensions too? As an extension will only ever ship with the app itself, so technically the same version number would be a good idea.

**Comment by Watson1978** [comment]
Before, when I tried to validate app which have extension, I succeeded. 
Maybe, this condition is added since Watch App.

**Comment by Watson1978** [comment]
@digitalfx I think your patch require similar changing about `app.short_version` too.

**Comment by digitalfx** [comment]
Hey @Watson1978 
This condition is only applied to the Watch App I believe. But when I started digging through various Extension Info.plist files I noticed that they all have v1.0, so thought that unless a dev specified a version, it would probably make sense to keep them all in sync through out an app?

Ah, yes you're right, short_version needs to be synced too!

**Comment by Watson1978** [comment]
Looks good to me. Thanks :)

**Comment by digitalfx** [comment]
:+1:

**Pull request merged**
