### PR TITLE
Frameworks require all embedded code to be signed.

### PR DESCRIPTION
**Pull request by digitalmoksha**
On OS X, if we're signing a vendored framework, then we need to include the `--deep` flag on the codesign to ensure that any nested code content such as helpers, frameworks, and plug-ins are also signed (requirement since Mavericks).  The same identity to sign the framework is used to the sign the nested code.

### CODE REVIEW

**Comment by digitalmoksha** [comment]
@Watson1978 Hmm, I may have boinked up this pull request when trying to rebase it on 4.0.  However, this fix is still needed in 4.x.  Otherwise embedded frameworks are not codesigned on OSX.  I get hit by this every time I upgrade RubyMotion.

The only file that changed is `lib/motion/project/template/osx/builder.rb`

**Comment by Watson1978** [comment]
It is better if you would clean up & rebase your pull request

**Comment by digitalmoksha** [comment]
@Watson1978 I can do that.  Can you cancel this pull request, and I'll generate another one...

**Comment by digitalmoksha** [comment]
@Watson1978 I just generated the pull request for this, #232

**Pull request closed without merging**
